
build:
  test-unit:
    image: tannv85/maven3.9-jdk8
    volumes:
      - target:/opt/tomcat/webapps
    commands:
      - mvn clean site
      - mkdir .framgia-ci-reports
      - mkdir .framgia-ci-reports/coverage
      - cp -r target/site/* .framgia-ci-reports/coverage
    when:
      event: [push, tag, pull_request]

  test-intergard:
      image: tannv85/maven3.9-jdk8
      volumes:
        - target:/opt/tomcat/webapps
      commands:
        - mvn clean install
        - mvn sonar:sonar -Dsonar.host.url=http://10.0.1.140:9000
        - mkdir .framgia-ci-reports
        - mkdir .framgia-ci-reports/unit-test

        - cp -r target/surefire-reports/* .framgia-ci-reports/unit-test
      when:
        event: [push, tag, pull_request]

compose:
  database:
    image: mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_pw
      MYSQL_ROOT_PASSWORD: root

cache:
  mount:
    - .git
    - /drone/.m2

debug: true