
build:
  test-unit:
    image: tannv85/maven3.9-jdk8
    volumes:
      - target:/opt/tomcat/webapps
    commands:
      - mvn clean site
      - mkdir .framgia-ci-reports
      - mkdir .framgia-ci-reports/coverage
      - cp -r target/site/* .framgia-ci-reports/coverage
      - framgia-ci run
    when:
      event: [push, tag, pull_request]
deploy:
  ssh:
    host: 10.0.1.139
    user: speeda
    port: 22
    commands:
      - cd apache-tomcat-8.0.20/webapps/
      - pwd
compose:
  database:
    image: tannv85/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: coffee
      MYSQL_ROOT_PASSWORD: tannv

cache:
  mount:
    - .git
    - /drone/.m2

debug: true

