
build:
  test-unit:
    image: tannv85/maven3.9-jdk8
    volumes:
      - target:/opt/tomcat/webapps
    commands:
      - framgia-ci run
    when:
      event: [push, tag, pull_request]

compose:
  database:
    image: tannv85/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: coffee
      MYSQL_ROOT_PASSWORD: tannv

cache:
  mount:
    - /drone/.git
    - /drone/.m2

debug: true

