
build:
  test-unit:
    image: tannv85/maven3.9-jdk8
    volumes:
      - target:/opt/tomcat/webapps
    commands:
      - framgia-ci run

    when:
      event: [push, tag, pull_request]

publish:
  ssh:
    host: 10.0.1.139
    user: speeda
    port: 22
    commands:
      - cd apache-tomcat-8.0.20/webapps/
      - rm -rf coffee*
  sftp:
    host: 10.0.1.139
    port: 22
    username: speeda
    files:
      - target/coffee.war
    destination_path: /home/speeda/apache-tomcat-8.0.20/webapps
    when:
      status: success

compose:
  database:
    image: tannv85/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: coffee
      MYSQL_ROOT_PASSWORD: tannv

cache:
  mount:
    - .git
    - .m2
debug: true

