
build:
  test-unit:
    image: tannv85/maven3.9-jdk8
    volumes:
      - target:/opt/tomcat/webapps
    commands:
      - mvn help:evaluate -Dexpression=settings.localRepository | grep -v '\[INFO\]'
      - mvn clean site -Dmaven.repo.local=$HOME/.m2/repository
      - mkdir .framgia-ci-reports
      - mkdir .framgia-ci-reports/coverage
      - cp -r target/site/* .framgia-ci-reports/coverage
      - framgia-ci run
      - cp -r target/coffee.war /drone/target/
    when:
      event: [push, tag, pull_request]

publish:
  sftp:
    host: 10.0.1.139
    port: 22
    username: speeda
    files:
      - /drone/target/coffee.war
    destination_path: /home/speeda/apache-tomcat-8.0.20/webapps
    when:
      status: success

deploy:
  ssh:
    host: 10.0.1.139
    user: speeda
    port: 22
    commands:
      - cd apache-tomcat-8.0.20/webapps/
      - pwd

compose:
  database:
    image: tannv85/mysql
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: coffee
      MYSQL_ROOT_PASSWORD: tannv

cache:
  mount:
    - .git
    - /drone/target
    - /drone/.m2

debug: true

