project_type: java
test:
 mvn:
   ignore: true
 command:
   - mvn clean site
   - mkdir .framgia-ci-reports
   - mkdir .framgia-ci-reports/coverage
   - cp -r target/site/* .framgia-ci-reports/coverage
   - framgia-ci upload