project_type: java
test:
  mvn:
    ignore: true
    command:
       - ls -la
       - mvn clean site -Dmaven.repo.local=.m2/repository
       - mkdir .framgia-ci-reports
       - mkdir .framgia-ci-reports/coverage
       - cp -r target/site/* .framgia-ci-reports/coverage